[package]
name = "nvmetcfg"
version = "0.1.0"
authors = ["Adrian 'vifino' Pistol <vifino@posteo.net>"]
license = "ISC"
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
thiserror = "1.0.50"
uuid = "1.5.0"
