name: Nix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: "system-features = nixos-test benchmark big-parallel kvm"
    - name: Setup Magic Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Run Flake Checks
      run: nix flake check -L
