name: Nix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # aarch64-linux and friends require emulation, which is terribly slow.
        # so slow, that the test doesn't pass.
        # TODO: set up aarch64 worker?
        system: [x86_64-linux, i686-linux]
        check: [loop, tcp, rdma]
        exclude:
          # Failed to find module 'rdma_rxe'
          - system: i686-linux
            check: rdma
    name: ${{ matrix.system }} - ${{ matrix.check }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup QEMU User and binfmt
      uses: docker/setup-qemu-action@v3
      if: ${{ matrix.system != 'x86_64-linux' && matrix.system != 'i686-linux' }}
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: "extra-platforms = ${{ matrix.system }}"
    - name: Setup Magic Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Run Flake Check
      run: nix build -L .#checks.${{ matrix.system }}.${{ matrix.check }}
