name: Nix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: [x86_64-linux, i686-linux]
        check: [loop, tcp, rdma]
        exclude:
          # Failed to find module 'rdma_rxe'
          - system: i686-linux
            check: rdma
    name: ${{ matrix.system }} - ${{ matrix.check }}
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Setup Magic Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Run Flake Check
      run: nix build -L .#checks.${{ matrix.system }}.${{ matrix.check }}
