name: Static

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: [x86_64, i686, aarch64]
    name: ${{ matrix.system }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup QEMU User and binfmt
      uses: docker/setup-qemu-action@v3
      if: ${{ matrix.system != 'x86_64' && matrix.system != 'i686' }}
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: "extra-platforms = ${{ matrix.system }}-linux"
    - name: Setup Magic Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build static binary
      run: |
        FLAKEREF=.#packages.${{ matrix.system }}-linux.nvmetcfg-static
        nix build -L $FLAKEREF
        echo "nvmetBinary=$(nix eval --raw $FLAKEREF)/bin/nvmet" >> $GITHUB_ENV
    - name: Upload workflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nvmet-${{ matrix.system }}
        path: ${{ env.nvmetBinary }}
